// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

import (
	"time"
)

// ActiveUser — Read-only row from view public.active_users.
type ActiveUser struct {
	ID       *int64     `db:"id" json:"id"`
	Email    *string    `db:"email" json:"email"`
	LastSeen *time.Time `db:"last_seen" json:"last_seen"`
}
