// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

/** Row from public.posts. */
export interface Post {
  id: bigint;
  title: string;
  tags: string[] | undefined;
  view_count: number;
}

/** Application user accounts. */
export interface User {
  /** Stable user identifier. */
  id: bigint;
  /** Unique login email. */
  email: string;
  display_name: string | undefined;
  role: UserRole;
  created_at: Date;
  deleted_at: Date | undefined;
  metadata: unknown | undefined;
}

