package differ

import (
	"strings"
	"testing"

	"github.com/nex-gen-tech/pg-flux/pkg/schema"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestDiffIdentity_addToPlainColumn(t *testing.T) {
	des := &schema.SchemaState{Tables: map[string]*schema.Table{
		"public.t": {Schema: "public", Name: "t", Columns: []*schema.Column{
			{Name: "id", TypeSQL: "bigint", NotNull: true, Identity: "by-default"},
		}},
	}}
	live := &schema.SchemaState{Tables: map[string]*schema.Table{
		"public.t": {Schema: "public", Name: "t", Columns: []*schema.Column{
			{Name: "id", TypeSQL: "bigint", NotNull: true},
		}},
	}}
	dr, err := Diff(des, live, Options{})
	require.NoError(t, err)
	var saw bool
	for _, s := range dr.Plan.Statements {
		if s.OpType == "ADD_IDENTITY" {
			saw = true
			assert.Contains(t, s.DDL, "ADD GENERATED BY DEFAULT AS IDENTITY")
		}
	}
	assert.True(t, saw, "expected ADD_IDENTITY")
}

func TestDiffIdentity_dropFromIdentityColumn(t *testing.T) {
	des := &schema.SchemaState{Tables: map[string]*schema.Table{
		"public.t": {Schema: "public", Name: "t", Columns: []*schema.Column{
			{Name: "id", TypeSQL: "bigint", NotNull: true},
		}},
	}}
	live := &schema.SchemaState{Tables: map[string]*schema.Table{
		"public.t": {Schema: "public", Name: "t", Columns: []*schema.Column{
			{Name: "id", TypeSQL: "bigint", NotNull: true, Identity: "always"},
		}},
	}}
	dr, err := Diff(des, live, Options{})
	require.NoError(t, err)
	var saw bool
	for _, s := range dr.Plan.Statements {
		if s.OpType == "DROP_IDENTITY" {
			saw = true
			assert.Contains(t, s.DDL, "DROP IDENTITY IF EXISTS")
		}
	}
	assert.True(t, saw, "expected DROP_IDENTITY")
}

func TestDiffIdentity_flipAlwaysToByDefault(t *testing.T) {
	des := &schema.SchemaState{Tables: map[string]*schema.Table{
		"public.t": {Schema: "public", Name: "t", Columns: []*schema.Column{
			{Name: "id", TypeSQL: "bigint", NotNull: true, Identity: "by-default"},
		}},
	}}
	live := &schema.SchemaState{Tables: map[string]*schema.Table{
		"public.t": {Schema: "public", Name: "t", Columns: []*schema.Column{
			{Name: "id", TypeSQL: "bigint", NotNull: true, Identity: "always"},
		}},
	}}
	dr, err := Diff(des, live, Options{})
	require.NoError(t, err)
	var saw bool
	for _, s := range dr.Plan.Statements {
		if s.OpType == "SET_IDENTITY" {
			saw = true
			assert.Contains(t, s.DDL, "SET GENERATED BY DEFAULT")
		}
	}
	assert.True(t, saw, "expected SET_IDENTITY")
}

func TestCreateTable_emitsIdentityClause(t *testing.T) {
	t1 := &schema.Table{Schema: "public", Name: "t", Columns: []*schema.Column{
		{Name: "id", TypeSQL: "bigint", NotNull: true, Identity: "by-default", IsPrimaryKey: true},
		{Name: "email", TypeSQL: "text", NotNull: true},
	}}
	sql := createTableSQL(t1)
	assert.True(t, strings.Contains(sql, "GENERATED BY DEFAULT AS IDENTITY"), "expected IDENTITY clause in DDL: %q", sql)
	// IDENTITY implies NOT NULL — confirm we don't double-emit:
	idCount := strings.Count(sql, "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	assert.Equal(t, 1, idCount, "expected single IDENTITY+PK form for id column; got:\n%s", sql)
}

func TestIdentityClause(t *testing.T) {
	assert.Equal(t, "ALWAYS", identityClause("always"))
	assert.Equal(t, "BY DEFAULT", identityClause("by-default"))
	assert.Equal(t, "", identityClause(""))
}
