-- IDENTITY columns: the modern (PG10+) replacement for serial/bigserial.
-- Both ALWAYS and BY DEFAULT forms should roundtrip with no diff.

CREATE TABLE public.identity_demo (
  id        bigint   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- ALWAYS form: callers MUST NOT supply this value (unless OVERRIDING SYSTEM VALUE).
  ordinal   integer  GENERATED ALWAYS    AS IDENTITY,
  label     text     NOT NULL
);
