// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

import (
	"database/sql/driver"
	"fmt"
)

// UserRole mirrors PG enum public.user_role.
type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleMember UserRole = "member"
	UserRoleGuest  UserRole = "guest"
)

// Scan implements sql.Scanner for UserRole.
func (e *UserRole) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		return nil
	case string:
		*e = UserRole(v)
		return nil
	case []byte:
		*e = UserRole(string(v))
		return nil
	}
	return fmt.Errorf("unsupported scan type for UserRole: %T", src)
}

// Value implements driver.Valuer for UserRole.
func (e UserRole) Value() (driver.Value, error) { return string(e), nil }
