// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

import (
	"encoding/json"
	"time"
)

// Post mirrors public.posts.
type Post struct {
	ID        int64     `bun:"id,pk" json:"id"`
	Title     string    `bun:"title" json:"title"`
	Tags      *[]string `bun:"tags,nullzero" json:"tags"`
	ViewCount int32     `bun:"view_count" json:"view_count"`
}

// TableName implements the bun table-name interface.
func (Post) TableName() string { return "public.posts" }

// User — Application user accounts.
type User struct {
	// Stable user identifier.
	ID int64 `bun:"id,pk" json:"id"`
	// Unique login email.
	Email       string           `bun:"email" json:"email"`
	DisplayName *string          `bun:"display_name,nullzero" json:"display_name"`
	Role        UserRole         `bun:"role" json:"role"`
	CreatedAt   time.Time        `bun:"created_at" json:"created_at"`
	DeletedAt   *time.Time       `bun:"deleted_at,nullzero" json:"deleted_at"`
	Metadata    *json.RawMessage `bun:"metadata,nullzero" json:"metadata"`
}

// TableName implements the bun table-name interface.
func (User) TableName() string { return "public.users" }
