// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

// Address mirrors composite type public.address.
type Address struct {
	Street string `db:"street" json:"street"`
	City   string `db:"city" json:"city"`
	Zip    string `db:"zip" json:"zip"`
}

// ShortText mirrors domain public.short_text over text.
type ShortText = string
