// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

import (
	"time"
)

// ActiveUser — Read-only row from view public.active_users.
type ActiveUser struct {
	ID       *int64     `bun:"id,nullzero" json:"id"`
	Email    *string    `bun:"email,nullzero" json:"email"`
	LastSeen *time.Time `bun:"last_seen,nullzero" json:"last_seen"`
}
