package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/nexg/pg-flux/pkg/schema"
)

// GoGenerator emits Go type definitions. ORM tag flavor, omitempty rules,
// readonly markers, and Scanner/Valuer methods for enums are all controlled
// by EmitOptions.
type GoGenerator struct {
	NameOverrides map[string]string
}

func NewGoGenerator() *GoGenerator { return &GoGenerator{} }

func (g *GoGenerator) Lang() Language { return LangGo }

func (g *GoGenerator) Generate(s *schema.SchemaState, opts Options) (FileSet, error) {
	if s == nil {
		return FileSet{}, nil
	}
	opts.Emit.normalize()
	s = opts.Emit.Filter.ApplyToState(s)

	if opts.Package == "" {
		opts.Package = "dbgen"
	}
	tm := opts.TypeMap
	if tm == nil {
		tm = &GoTypeMap{}
	}
	if gtm, ok := tm.(*GoTypeMap); ok {
		gtm.CustomTypes = g.collectCustomTypes(s)
	}
	out := FileSet{}

	add := func(name string, content string) error {
		formatted, ferr := format.Source([]byte(content))
		if ferr != nil {
			out[name] = []byte(content)
			return fmt.Errorf("%s: gofmt: %w", name, ferr)
		}
		out[name] = formatted
		return nil
	}
	if b, imps, ok := g.emitTables(s, tm, opts); ok {
		if err := add("tables.go", g.fileHeader(opts.Package, imps)+b); err != nil {
			return out, err
		}
	}
	if b, imps, ok := g.emitEnums(s, opts); ok {
		if err := add("enums.go", g.fileHeader(opts.Package, imps)+b); err != nil {
			return out, err
		}
	}
	if b, imps, ok := g.emitTypes(s, tm, opts); ok {
		if err := add("types.go", g.fileHeader(opts.Package, imps)+b); err != nil {
			return out, err
		}
	}
	if b, imps, ok := g.emitViews(s, tm, opts); ok {
		if err := add("views.go", g.fileHeader(opts.Package, imps)+b); err != nil {
			return out, err
		}
	}
	if b, imps, ok := g.emitGoFunctions(s, tm, opts); ok {
		if err := add("functions.go", g.fileHeader(opts.Package, imps)+b); err != nil {
			return out, err
		}
	}
	return out, nil
}

func (g *GoGenerator) fileHeader(pkg string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by pg-flux. DO NOT EDIT.\n")
	b.WriteString("// To regenerate, run: pg-flux gen\n\n")
	fmt.Fprintf(&b, "package %s\n", pkg)
	if len(imports) > 0 {
		uniq := uniqueSort(imports)
		b.WriteString("\nimport (\n")
		for _, imp := range uniq {
			fmt.Fprintf(&b, "\t%q\n", imp)
		}
		b.WriteString(")\n")
	}
	b.WriteString("\n")
	return b.String()
}

func (g *GoGenerator) typeName(schName, objName string) string {
	full := schName + "." + objName
	if g.NameOverrides != nil {
		if v, ok := g.NameOverrides[full]; ok {
			return v
		}
		if v, ok := g.NameOverrides[objName]; ok {
			return v
		}
	}
	return PascalCaseInit(Singular(objName))
}

func (g *GoGenerator) emitTables(s *schema.SchemaState, tm TypeMap, opts Options) (string, []string, bool) {
	if len(s.Tables) == 0 {
		return "", nil, false
	}
	var b strings.Builder
	var imports []string
	for _, k := range SortedKeys(s.Tables) {
		t := s.Tables[k]
		if t == nil {
			continue
		}
		body, imps := g.emitTableStruct(t, tm, opts)
		b.WriteString(body)
		b.WriteString("\n")
		imports = append(imports, imps...)
	}
	return b.String(), imports, true
}

func (g *GoGenerator) emitTableStruct(t *schema.Table, tm TypeMap, opts Options) (string, []string) {
	var b strings.Builder
	var imports []string
	typeName := g.typeName(t.Schema, t.Name)
	if t.Comment != "" {
		writeGoDoc(&b, typeName, t.Comment)
	} else {
		fmt.Fprintf(&b, "// %s mirrors %s.%s.\n", typeName, t.Schema, t.Name)
	}
	fmt.Fprintf(&b, "type %s struct {\n", typeName)
	for _, c := range t.Columns {
		if c == nil {
			continue
		}
		hints := ParseCommentHints(c.Comment)
		if hints.Doc != "" {
			fmt.Fprintf(&b, "\t// %s\n", hints.Doc)
		}
		if isReadonly(c, opts.Emit.Readonly) {
			b.WriteString("\t// readonly (server-managed)\n")
		}
		field := PascalCaseInit(c.Name)
		var typeExpr string
		var imps []string
		if override, ok := hints.Overrides["gotype"]; ok {
			typeExpr, imps = resolveQualifiedType(override)
			if !c.NotNull {
				typeExpr = "*" + typeExpr
			}
		} else {
			typeExpr, imps = tm.Map(c.TypeSQL, !c.NotNull)
		}
		imports = append(imports, imps...)
		tag := buildGoTag(c, opts.Emit)
		fmt.Fprintf(&b, "\t%s %s %s\n", field, typeExpr, tag)
	}
	b.WriteString("}\n")

	// Optional TableName() method when ORM tags request it (gorm, bun benefit).
	if opts.Emit.ORMTags == "gorm" || opts.Emit.ORMTags == "bun" {
		fmt.Fprintf(&b, "\n// TableName implements the %s table-name interface.\n", opts.Emit.ORMTags)
		fmt.Fprintf(&b, "func (%s) TableName() string { return %q }\n", typeName, t.Schema+"."+t.Name)
	}
	return b.String(), imports
}

// buildGoTag composes the struct tag honouring orm_tags and omitempty.
// Default: `db:"col" json:"col"`. sqlx mode drops the json tag (sqlx ignores
// it). gorm adds gorm-specific tags. bun mirrors bun's convention.
func buildGoTag(c *schema.Column, eo EmitOptions) string {
	col := c.Name
	dbKey := eo.ApplyColumnCase(col)
	jsonKey := eo.ApplyColumnCase(col)
	jsonSuffix := ""
	switch eo.OmitEmpty {
	case "nullable":
		if !c.NotNull {
			jsonSuffix = ",omitempty"
		}
	case "defaults":
		if !c.NotNull || c.DefaultSQL != "" || c.Identity != "" || c.GeneratedKind != "" {
			jsonSuffix = ",omitempty"
		}
	case "all":
		jsonSuffix = ",omitempty"
	}
	var parts []string
	switch eo.ORMTags {
	case "sqlx":
		parts = append(parts, fmt.Sprintf("db:%q", dbKey))
	case "gorm":
		gormParts := []string{"column:" + col}
		if c.IsPrimaryKey {
			gormParts = append(gormParts, "primaryKey")
		}
		if c.Identity != "" || strings.Contains(strings.ToLower(c.TypeSQL), "serial") {
			gormParts = append(gormParts, "autoIncrement")
		}
		if c.NotNull {
			gormParts = append(gormParts, "not null")
		}
		if c.DefaultSQL != "" {
			gormParts = append(gormParts, "default:"+c.DefaultSQL)
		}
		parts = append(parts,
			fmt.Sprintf("db:%q", dbKey),
			fmt.Sprintf("gorm:%q", strings.Join(gormParts, ";")),
			fmt.Sprintf("json:\"%s%s\"", jsonKey, jsonSuffix),
		)
	case "bun":
		bunParts := []string{col}
		if c.IsPrimaryKey {
			bunParts = append(bunParts, "pk")
		}
		if c.Identity != "" || strings.Contains(strings.ToLower(c.TypeSQL), "serial") {
			bunParts = append(bunParts, "autoincrement")
		}
		if !c.NotNull {
			bunParts = append(bunParts, "nullzero")
		}
		parts = append(parts,
			fmt.Sprintf("bun:%q", strings.Join(bunParts, ",")),
			fmt.Sprintf("json:\"%s%s\"", jsonKey, jsonSuffix),
		)
	case "ent":
		parts = append(parts,
			fmt.Sprintf("db:%q", dbKey),
			fmt.Sprintf("json:\"%s%s\"", jsonKey, jsonSuffix),
		)
	default:
		parts = append(parts,
			fmt.Sprintf("db:%q", dbKey),
			fmt.Sprintf("json:\"%s%s\"", jsonKey, jsonSuffix),
		)
	}
	return "`" + strings.Join(parts, " ") + "`"
}

func (g *GoGenerator) emitEnums(s *schema.SchemaState, opts Options) (string, []string, bool) {
	if len(s.EnumValues) == 0 {
		return "", nil, false
	}
	var b strings.Builder
	var imports []string
	emitScanValue := opts.Emit.ORMTags != "" // any ORM mode benefits from these
	for _, k := range SortedKeys(s.EnumValues) {
		values := s.EnumValues[k]
		parts := strings.SplitN(k, ".", 2)
		var schName, name string
		if len(parts) == 2 {
			schName, name = parts[0], parts[1]
		} else {
			schName, name = "public", parts[0]
		}
		typeName := g.typeName(schName, name)
		fmt.Fprintf(&b, "// %s mirrors PG enum %s.%s.\n", typeName, schName, name)
		fmt.Fprintf(&b, "type %s string\n\n", typeName)
		fmt.Fprintf(&b, "const (\n")
		for _, v := range values {
			constName := typeName + PascalCaseInit(v)
			fmt.Fprintf(&b, "\t%s %s = %q\n", constName, typeName, v)
		}
		b.WriteString(")\n\n")

		if emitScanValue {
			// Scan/Value methods so database/sql can round-trip the enum
			// transparently — important for gorm/sqlx/bun usage.
			fmt.Fprintf(&b, "// Scan implements sql.Scanner for %s.\n", typeName)
			fmt.Fprintf(&b, "func (e *%s) Scan(src any) error {\n", typeName)
			b.WriteString("\tswitch v := src.(type) {\n")
			b.WriteString("\tcase nil:\n\t\treturn nil\n")
			fmt.Fprintf(&b, "\tcase string:\n\t\t*e = %s(v)\n\t\treturn nil\n", typeName)
			fmt.Fprintf(&b, "\tcase []byte:\n\t\t*e = %s(string(v))\n\t\treturn nil\n", typeName)
			fmt.Fprintf(&b, "\t}\n\treturn fmt.Errorf(\"unsupported scan type for %s: %%T\", src)\n}\n\n", typeName)
			fmt.Fprintf(&b, "// Value implements driver.Valuer for %s.\n", typeName)
			fmt.Fprintf(&b, "func (e %s) Value() (driver.Value, error) { return string(e), nil }\n\n", typeName)
			imports = append(imports, "database/sql/driver", "fmt")
		}
	}
	return b.String(), imports, true
}

func (g *GoGenerator) emitTypes(s *schema.SchemaState, tm TypeMap, opts Options) (string, []string, bool) {
	if len(s.CompositeTypes) == 0 && len(s.Domains) == 0 {
		return "", nil, false
	}
	var b strings.Builder
	var imports []string
	for _, k := range SortedKeys(s.CompositeTypes) {
		ct := s.CompositeTypes[k]
		if ct == nil {
			continue
		}
		typeName := g.typeName(ct.Schema, ct.Name)
		if ct.Comment != "" {
			writeGoDoc(&b, typeName, ct.Comment)
		} else {
			fmt.Fprintf(&b, "// %s mirrors composite type %s.%s.\n", typeName, ct.Schema, ct.Name)
		}
		fmt.Fprintf(&b, "type %s struct {\n", typeName)
		for _, a := range ct.Attributes {
			field := PascalCaseInit(a.Name)
			typeExpr, imps := tm.Map(a.Type, false)
			imports = append(imports, imps...)
			key := opts.Emit.ApplyColumnCase(a.Name)
			fmt.Fprintf(&b, "\t%s %s `db:%q json:%q`\n", field, typeExpr, key, key)
		}
		b.WriteString("}\n\n")
	}
	for _, k := range SortedKeys(s.Domains) {
		d := s.Domains[k]
		if d == nil {
			continue
		}
		typeName := g.typeName(d.Schema, d.Name)
		baseExpr, imps := tm.Map(d.BaseType, false)
		imports = append(imports, imps...)
		fmt.Fprintf(&b, "// %s mirrors domain %s.%s over %s.\n", typeName, d.Schema, d.Name, d.BaseType)
		fmt.Fprintf(&b, "type %s = %s\n\n", typeName, baseExpr)
	}
	return b.String(), imports, true
}

func (g *GoGenerator) emitViews(s *schema.SchemaState, tm TypeMap, opts Options) (string, []string, bool) {
	if len(s.Views) == 0 {
		return "", nil, false
	}
	var b strings.Builder
	var imports []string
	for _, k := range SortedKeys(s.Views) {
		v := s.Views[k]
		if v == nil {
			continue
		}
		typeName := g.typeName(v.Schema, v.Name)
		kw := "view"
		if v.Materialized {
			kw = "materialized view"
		}
		comment := v.Comment
		if comment == "" {
			comment = fmt.Sprintf("Read-only row from %s %s.%s.", kw, v.Schema, v.Name)
		}
		writeGoDoc(&b, typeName, comment)
		fmt.Fprintf(&b, "type %s struct {\n", typeName)
		fmt.Fprintf(&b, "\t// fields: not yet inferred from view definition;\n")
		fmt.Fprintf(&b, "\t// add manually or override via codegen config.\n")
		b.WriteString("}\n\n")
	}
	return b.String(), imports, true
}

func writeGoDoc(b *strings.Builder, name, comment string) {
	lines := strings.Split(strings.TrimSpace(comment), "\n")
	if len(lines) == 0 {
		return
	}
	first := strings.TrimSpace(lines[0])
	if !strings.HasPrefix(first, name) {
		fmt.Fprintf(b, "// %s — %s\n", name, first)
	} else {
		fmt.Fprintf(b, "// %s\n", first)
	}
	for _, line := range lines[1:] {
		fmt.Fprintf(b, "// %s\n", strings.TrimSpace(line))
	}
}

func uniqueSort(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	m := map[string]struct{}{}
	for _, s := range in {
		if s != "" {
			m[s] = struct{}{}
		}
	}
	out := make([]string, 0, len(m))
	for s := range m {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

// collectCustomTypes builds the user-defined-type → generated-identifier map
// so the typemap can resolve column refs to enums/composites/domains.
func (g *GoGenerator) collectCustomTypes(s *schema.SchemaState) map[string]string {
	if s == nil {
		return nil
	}
	out := map[string]string{}
	for k := range s.EnumValues {
		parts := strings.SplitN(k, ".", 2)
		var sch, n string
		if len(parts) == 2 {
			sch, n = parts[0], parts[1]
		} else {
			sch, n = "public", parts[0]
		}
		ident := g.typeName(sch, n)
		out[k] = ident
		out[n] = ident
	}
	for k, ct := range s.CompositeTypes {
		if ct == nil {
			continue
		}
		ident := g.typeName(ct.Schema, ct.Name)
		out[k] = ident
		out[ct.Name] = ident
	}
	for k, d := range s.Domains {
		if d == nil {
			continue
		}
		ident := g.typeName(d.Schema, d.Name)
		out[k] = ident
		out[d.Name] = ident
	}
	return out
}
