package codegen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/nexg/pg-flux/pkg/schema"
)

// GoGenerator emits Go type definitions for the pg-flux schema.
type GoGenerator struct {
	// NameOverrides forces a PG identifier to render as a specific Go type name.
	// Keys are "schema.name" or bare "name". Values are emitted verbatim.
	NameOverrides map[string]string
}

// NewGoGenerator constructs a Go generator. Defaults: stdlib-only type map,
// no name overrides.
func NewGoGenerator() *GoGenerator { return &GoGenerator{} }

// Lang implements Generator.
func (g *GoGenerator) Lang() Language { return LangGo }

// Generate implements Generator. Emits one file per object kind:
//   - tables.go (one struct per table, with db + json tags)
//   - enums.go  (string-typed type alias + constants)
//   - types.go  (composite types + domain aliases)
//   - views.go  (one struct per view; read-only)
//
// Files with no content are omitted (e.g., no enums.go when the schema has
// no enums) so generated trees stay tidy.
func (g *GoGenerator) Generate(s *schema.SchemaState, opts Options) (FileSet, error) {
	if s == nil {
		return FileSet{}, nil
	}
	if opts.Package == "" {
		opts.Package = "dbgen"
	}
	tm := opts.TypeMap
	if tm == nil {
		tm = &GoTypeMap{}
	}
	// Populate the typemap's custom-type lookup so column refs to enums,
	// composites, and domains resolve to the generated Go identifiers
	// instead of falling through to "string".
	if gtm, ok := tm.(*GoTypeMap); ok {
		gtm.CustomTypes = g.collectCustomTypes(s)
	}
	out := FileSet{}

	add := func(name string, content string) error {
		// Run gofmt so struct fields align, imports order, etc. Fall back to the
		// raw bytes if gofmt errors (lets the user inspect malformed emit).
		formatted, ferr := format.Source([]byte(content))
		if ferr != nil {
			out[name] = []byte(content)
			return fmt.Errorf("%s: gofmt: %w", name, ferr)
		}
		out[name] = formatted
		return nil
	}
	if b, imps, ok := g.emitTables(s, tm); ok {
		if err := add("tables.go", g.fileHeader(opts.Package, imps)+b); err != nil {
			return out, err
		}
	}
	if b, ok := g.emitEnums(s); ok {
		if err := add("enums.go", g.fileHeader(opts.Package, nil)+b); err != nil {
			return out, err
		}
	}
	if b, imps, ok := g.emitTypes(s, tm); ok {
		if err := add("types.go", g.fileHeader(opts.Package, imps)+b); err != nil {
			return out, err
		}
	}
	if b, imps, ok := g.emitViews(s, tm); ok {
		if err := add("views.go", g.fileHeader(opts.Package, imps)+b); err != nil {
			return out, err
		}
	}
	return out, nil
}

// fileHeader returns the package declaration + import block + standard "DO NOT
// EDIT" banner. imports may be empty.
func (g *GoGenerator) fileHeader(pkg string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by pg-flux. DO NOT EDIT.\n")
	b.WriteString("// To regenerate, run: pg-flux gen\n\n")
	fmt.Fprintf(&b, "package %s\n", pkg)
	if len(imports) > 0 {
		uniq := uniqueSort(imports)
		b.WriteString("\nimport (\n")
		for _, imp := range uniq {
			fmt.Fprintf(&b, "\t%q\n", imp)
		}
		b.WriteString(")\n")
	}
	b.WriteString("\n")
	return b.String()
}

// collectCustomTypes builds the user-defined-type → generated-identifier map
// so the typemap can resolve column refs (e.g., role user_role NOT NULL →
// Role UserRole) instead of falling through to "string".
func (g *GoGenerator) collectCustomTypes(s *schema.SchemaState) map[string]string {
	if s == nil {
		return nil
	}
	out := map[string]string{}
	for k := range s.EnumValues {
		parts := strings.SplitN(k, ".", 2)
		var sch, n string
		if len(parts) == 2 {
			sch, n = parts[0], parts[1]
		} else {
			sch, n = "public", parts[0]
		}
		ident := g.typeName(sch, n)
		out[k] = ident
		out[n] = ident // bare-name fallback
	}
	for k, ct := range s.CompositeTypes {
		if ct == nil {
			continue
		}
		ident := g.typeName(ct.Schema, ct.Name)
		out[k] = ident
		out[ct.Name] = ident
	}
	for k, d := range s.Domains {
		if d == nil {
			continue
		}
		ident := g.typeName(d.Schema, d.Name)
		out[k] = ident
		out[d.Name] = ident
	}
	return out
}

// typeName resolves the Go identifier for a (schema, name) pair. Default rule:
// singularize the table name then PascalCaseInit. Overrides win.
func (g *GoGenerator) typeName(schName, objName string) string {
	full := schName + "." + objName
	if g.NameOverrides != nil {
		if v, ok := g.NameOverrides[full]; ok {
			return v
		}
		if v, ok := g.NameOverrides[objName]; ok {
			return v
		}
	}
	return PascalCaseInit(Singular(objName))
}

// emitTables renders all tables as Go structs. Returns the body, aggregated
// imports, and ok=false when there are no tables.
func (g *GoGenerator) emitTables(s *schema.SchemaState, tm TypeMap) (string, []string, bool) {
	if len(s.Tables) == 0 {
		return "", nil, false
	}
	var b strings.Builder
	var imports []string
	for _, k := range SortedKeys(s.Tables) {
		t := s.Tables[k]
		if t == nil {
			continue
		}
		body, imps := g.emitTableStruct(t, tm)
		b.WriteString(body)
		b.WriteString("\n")
		imports = append(imports, imps...)
	}
	return b.String(), imports, true
}

func (g *GoGenerator) emitTableStruct(t *schema.Table, tm TypeMap) (string, []string) {
	var b strings.Builder
	var imports []string
	typeName := g.typeName(t.Schema, t.Name)
	if t.Comment != "" {
		writeGoDoc(&b, typeName, t.Comment)
	} else {
		fmt.Fprintf(&b, "// %s mirrors %s.%s.\n", typeName, t.Schema, t.Name)
	}
	fmt.Fprintf(&b, "type %s struct {\n", typeName)
	// Column-name → field-name with column doc.
	for _, c := range t.Columns {
		if c == nil {
			continue
		}
		hints := ParseCommentHints(c.Comment)
		if hints.Doc != "" {
			fmt.Fprintf(&b, "\t// %s\n", hints.Doc)
		}
		field := PascalCaseInit(c.Name)
		// Per-column gotype override has highest precedence.
		var typeExpr string
		var imps []string
		if override, ok := hints.Overrides["gotype"]; ok {
			typeExpr, imps = resolveQualifiedType(override)
			if !c.NotNull {
				typeExpr = "*" + typeExpr
			}
		} else {
			typeExpr, imps = tm.Map(c.TypeSQL, !c.NotNull)
		}
		imports = append(imports, imps...)
		tag := fmt.Sprintf("`db:\"%s\" json:\"%s\"`", c.Name, c.Name)
		fmt.Fprintf(&b, "\t%s %s %s\n", field, typeExpr, tag)
	}
	b.WriteString("}\n")
	return b.String(), imports
}

// emitEnums renders enum types as string-typed aliases plus typed constants.
func (g *GoGenerator) emitEnums(s *schema.SchemaState) (string, bool) {
	if len(s.EnumValues) == 0 {
		return "", false
	}
	var b strings.Builder
	for _, k := range SortedKeys(s.EnumValues) {
		values := s.EnumValues[k]
		parts := strings.SplitN(k, ".", 2)
		var schName, name string
		if len(parts) == 2 {
			schName, name = parts[0], parts[1]
		} else {
			schName, name = "public", parts[0]
		}
		typeName := g.typeName(schName, name)
		fmt.Fprintf(&b, "// %s mirrors PG enum %s.%s.\n", typeName, schName, name)
		fmt.Fprintf(&b, "type %s string\n\n", typeName)
		fmt.Fprintf(&b, "const (\n")
		for _, v := range values {
			constName := typeName + PascalCaseInit(v)
			fmt.Fprintf(&b, "\t%s %s = %q\n", constName, typeName, v)
		}
		b.WriteString(")\n\n")
	}
	return b.String(), true
}

// emitTypes renders composite types and domain aliases.
func (g *GoGenerator) emitTypes(s *schema.SchemaState, tm TypeMap) (string, []string, bool) {
	if len(s.CompositeTypes) == 0 && len(s.Domains) == 0 {
		return "", nil, false
	}
	var b strings.Builder
	var imports []string
	for _, k := range SortedKeys(s.CompositeTypes) {
		ct := s.CompositeTypes[k]
		if ct == nil {
			continue
		}
		typeName := g.typeName(ct.Schema, ct.Name)
		if ct.Comment != "" {
			writeGoDoc(&b, typeName, ct.Comment)
		} else {
			fmt.Fprintf(&b, "// %s mirrors composite type %s.%s.\n", typeName, ct.Schema, ct.Name)
		}
		fmt.Fprintf(&b, "type %s struct {\n", typeName)
		for _, a := range ct.Attributes {
			field := PascalCaseInit(a.Name)
			typeExpr, imps := tm.Map(a.Type, false)
			imports = append(imports, imps...)
			fmt.Fprintf(&b, "\t%s %s `db:\"%s\" json:\"%s\"`\n", field, typeExpr, a.Name, a.Name)
		}
		b.WriteString("}\n\n")
	}
	for _, k := range SortedKeys(s.Domains) {
		d := s.Domains[k]
		if d == nil {
			continue
		}
		typeName := g.typeName(d.Schema, d.Name)
		baseExpr, imps := tm.Map(d.BaseType, false)
		imports = append(imports, imps...)
		fmt.Fprintf(&b, "// %s mirrors domain %s.%s over %s.\n", typeName, d.Schema, d.Name, d.BaseType)
		fmt.Fprintf(&b, "type %s = %s\n\n", typeName, baseExpr)
	}
	return b.String(), imports, true
}

// emitViews renders views as read-only structs.
func (g *GoGenerator) emitViews(s *schema.SchemaState, tm TypeMap) (string, []string, bool) {
	if len(s.Views) == 0 {
		return "", nil, false
	}
	var b strings.Builder
	var imports []string
	for _, k := range SortedKeys(s.Views) {
		v := s.Views[k]
		if v == nil {
			continue
		}
		typeName := g.typeName(v.Schema, v.Name)
		kw := "view"
		if v.Materialized {
			kw = "materialized view"
		}
		comment := v.Comment
		if comment == "" {
			comment = fmt.Sprintf("Read-only row from %s %s.%s.", kw, v.Schema, v.Name)
		}
		writeGoDoc(&b, typeName, comment)
		// Views don't currently track column types in the model (they're
		// inferred from pg_get_viewdef), so we cannot emit fields here.
		// Marker struct with a TODO comment so downstream tooling sees the
		// existence of the view; richer view-column extraction is future work.
		fmt.Fprintf(&b, "type %s struct {\n", typeName)
		fmt.Fprintf(&b, "\t// fields: not yet inferred from view definition;\n")
		fmt.Fprintf(&b, "\t// add manually or override via codegen config.\n")
		b.WriteString("}\n\n")
	}
	return b.String(), imports, true
}

// writeGoDoc emits one or more "// " comment lines for a multi-line comment so
// each generated type carries its database-level documentation.
func writeGoDoc(b *strings.Builder, name, comment string) {
	lines := strings.Split(strings.TrimSpace(comment), "\n")
	if len(lines) == 0 {
		return
	}
	// Conventional Godoc starts the comment with the identifier name.
	first := strings.TrimSpace(lines[0])
	if !strings.HasPrefix(first, name) {
		fmt.Fprintf(b, "// %s — %s\n", name, first)
	} else {
		fmt.Fprintf(b, "// %s\n", first)
	}
	for _, line := range lines[1:] {
		fmt.Fprintf(b, "// %s\n", strings.TrimSpace(line))
	}
}

// uniqueSort dedupes and stable-sorts a string slice (used for import lists).
func uniqueSort(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	m := map[string]struct{}{}
	for _, s := range in {
		if s != "" {
			m[s] = struct{}{}
		}
	}
	out := make([]string, 0, len(m))
	for s := range m {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}
