package codegen

import (
	"fmt"
	"strings"

	"github.com/nexg/pg-flux/pkg/schema"
)

// TSGenerator emits TypeScript interface and type-alias definitions.
type TSGenerator struct {
	NameOverrides map[string]string
}

func NewTSGenerator() *TSGenerator { return &TSGenerator{} }

func (g *TSGenerator) Lang() Language { return LangTypeScript }

// Generate emits one file per object kind plus an index.ts barrel that re-
// exports everything for easy "import { User } from 'dbgen'" consumption.
func (g *TSGenerator) Generate(s *schema.SchemaState, opts Options) (FileSet, error) {
	if s == nil {
		return FileSet{}, nil
	}
	tm := opts.TypeMap
	if tm == nil {
		tm = &TSTypeMap{}
	}
	if ttm, ok := tm.(*TSTypeMap); ok {
		ttm.CustomTypes = g.collectCustomTypes(s)
	}
	out := FileSet{}
	hasTables := false
	hasEnums := false
	hasTypes := false
	hasViews := false

	if b, ok := g.emitTables(s, tm); ok {
		out["tables.ts"] = []byte(g.fileHeader() + b)
		hasTables = true
	}
	if b, ok := g.emitEnums(s); ok {
		out["enums.ts"] = []byte(g.fileHeader() + b)
		hasEnums = true
	}
	if b, ok := g.emitTypes(s, tm); ok {
		out["types.ts"] = []byte(g.fileHeader() + b)
		hasTypes = true
	}
	if b, ok := g.emitViews(s, tm); ok {
		out["views.ts"] = []byte(g.fileHeader() + b)
		hasViews = true
	}

	if hasTables || hasEnums || hasTypes || hasViews {
		out["index.ts"] = []byte(g.barrel(hasTables, hasEnums, hasTypes, hasViews))
	}
	return out, nil
}

func (g *TSGenerator) fileHeader() string {
	return "// Code generated by pg-flux. DO NOT EDIT.\n" +
		"// To regenerate, run: pg-flux gen\n\n"
}

func (g *TSGenerator) barrel(tbl, enum, typ, view bool) string {
	var b strings.Builder
	b.WriteString(g.fileHeader())
	if tbl {
		b.WriteString("export * from './tables';\n")
	}
	if enum {
		b.WriteString("export * from './enums';\n")
	}
	if typ {
		b.WriteString("export * from './types';\n")
	}
	if view {
		b.WriteString("export * from './views';\n")
	}
	return b.String()
}

// collectCustomTypes is the TS equivalent of GoGenerator.collectCustomTypes.
func (g *TSGenerator) collectCustomTypes(s *schema.SchemaState) map[string]string {
	if s == nil {
		return nil
	}
	out := map[string]string{}
	for k := range s.EnumValues {
		parts := strings.SplitN(k, ".", 2)
		var sch, n string
		if len(parts) == 2 {
			sch, n = parts[0], parts[1]
		} else {
			sch, n = "public", parts[0]
		}
		ident := g.typeName(sch, n)
		out[k] = ident
		out[n] = ident
	}
	for k, ct := range s.CompositeTypes {
		if ct == nil {
			continue
		}
		ident := g.typeName(ct.Schema, ct.Name)
		out[k] = ident
		out[ct.Name] = ident
	}
	for k, d := range s.Domains {
		if d == nil {
			continue
		}
		ident := g.typeName(d.Schema, d.Name)
		out[k] = ident
		out[d.Name] = ident
	}
	return out
}

func (g *TSGenerator) typeName(schName, objName string) string {
	full := schName + "." + objName
	if g.NameOverrides != nil {
		if v, ok := g.NameOverrides[full]; ok {
			return v
		}
		if v, ok := g.NameOverrides[objName]; ok {
			return v
		}
	}
	return PascalCaseInit(Singular(objName))
}

func (g *TSGenerator) emitTables(s *schema.SchemaState, tm TypeMap) (string, bool) {
	if len(s.Tables) == 0 {
		return "", false
	}
	var b strings.Builder
	for _, k := range SortedKeys(s.Tables) {
		t := s.Tables[k]
		if t == nil {
			continue
		}
		typeName := g.typeName(t.Schema, t.Name)
		writeTSDoc(&b, t.Comment, fmt.Sprintf("Row from %s.%s.", t.Schema, t.Name))
		fmt.Fprintf(&b, "export interface %s {\n", typeName)
		for _, c := range t.Columns {
			if c == nil {
				continue
			}
			hints := ParseCommentHints(c.Comment)
			if hints.Doc != "" {
				fmt.Fprintf(&b, "  /** %s */\n", hints.Doc)
			}
			var typeExpr string
			if override, ok := hints.Overrides["tstype"]; ok {
				if !c.NotNull {
					typeExpr = override + " | null"
				} else {
					typeExpr = override
				}
			} else {
				typeExpr, _ = tm.Map(c.TypeSQL, !c.NotNull)
			}
			fmt.Fprintf(&b, "  %s: %s;\n", c.Name, typeExpr)
		}
		b.WriteString("}\n\n")
	}
	return b.String(), true
}

func (g *TSGenerator) emitEnums(s *schema.SchemaState) (string, bool) {
	if len(s.EnumValues) == 0 {
		return "", false
	}
	var b strings.Builder
	for _, k := range SortedKeys(s.EnumValues) {
		values := s.EnumValues[k]
		parts := strings.SplitN(k, ".", 2)
		var schName, name string
		if len(parts) == 2 {
			schName, name = parts[0], parts[1]
		} else {
			schName, name = "public", parts[0]
		}
		typeName := g.typeName(schName, name)
		fmt.Fprintf(&b, "/** PG enum %s.%s */\n", schName, name)
		fmt.Fprintf(&b, "export type %s =\n", typeName)
		for i, v := range values {
			suffix := ""
			if i == len(values)-1 {
				suffix = ";"
			}
			fmt.Fprintf(&b, "  | %q%s\n", v, suffix)
		}
		b.WriteString("\n")
	}
	return b.String(), true
}

func (g *TSGenerator) emitTypes(s *schema.SchemaState, tm TypeMap) (string, bool) {
	if len(s.CompositeTypes) == 0 && len(s.Domains) == 0 {
		return "", false
	}
	var b strings.Builder
	for _, k := range SortedKeys(s.CompositeTypes) {
		ct := s.CompositeTypes[k]
		if ct == nil {
			continue
		}
		typeName := g.typeName(ct.Schema, ct.Name)
		writeTSDoc(&b, ct.Comment, fmt.Sprintf("Composite type %s.%s.", ct.Schema, ct.Name))
		fmt.Fprintf(&b, "export interface %s {\n", typeName)
		for _, a := range ct.Attributes {
			typeExpr, _ := tm.Map(a.Type, false)
			fmt.Fprintf(&b, "  %s: %s;\n", a.Name, typeExpr)
		}
		b.WriteString("}\n\n")
	}
	for _, k := range SortedKeys(s.Domains) {
		d := s.Domains[k]
		if d == nil {
			continue
		}
		typeName := g.typeName(d.Schema, d.Name)
		baseExpr, _ := tm.Map(d.BaseType, false)
		fmt.Fprintf(&b, "/** Domain %s.%s over %s. */\n", d.Schema, d.Name, d.BaseType)
		fmt.Fprintf(&b, "export type %s = %s;\n\n", typeName, baseExpr)
	}
	return b.String(), true
}

func (g *TSGenerator) emitViews(s *schema.SchemaState, tm TypeMap) (string, bool) {
	if len(s.Views) == 0 {
		return "", false
	}
	var b strings.Builder
	for _, k := range SortedKeys(s.Views) {
		v := s.Views[k]
		if v == nil {
			continue
		}
		typeName := g.typeName(v.Schema, v.Name)
		kw := "view"
		if v.Materialized {
			kw = "materialized view"
		}
		fallback := fmt.Sprintf("Read-only row from %s %s.%s.", kw, v.Schema, v.Name)
		writeTSDoc(&b, v.Comment, fallback)
		fmt.Fprintf(&b, "export interface %s {\n", typeName)
		b.WriteString("  // fields: not yet inferred from view definition;\n")
		b.WriteString("  // add manually or override via codegen config.\n")
		b.WriteString("}\n\n")
	}
	return b.String(), true
}

func writeTSDoc(b *strings.Builder, comment, fallback string) {
	c := strings.TrimSpace(comment)
	if c == "" {
		c = fallback
	}
	if !strings.Contains(c, "\n") {
		fmt.Fprintf(b, "/** %s */\n", c)
		return
	}
	b.WriteString("/**\n")
	for _, line := range strings.Split(c, "\n") {
		fmt.Fprintf(b, " * %s\n", strings.TrimSpace(line))
	}
	b.WriteString(" */\n")
}
