// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

import (
	"encoding/json"
	"time"
)

// Post mirrors public.posts.
type Post struct {
	ID        int64     `db:"id" gorm:"column:id;primaryKey;not null" json:"id"`
	Title     string    `db:"title" gorm:"column:title;not null" json:"title"`
	Tags      *[]string `db:"tags" gorm:"column:tags" json:"tags,omitempty"`
	ViewCount int32     `db:"view_count" gorm:"column:view_count;not null;default:0" json:"view_count,omitempty"`
}

// TableName implements the gorm table-name interface.
func (Post) TableName() string { return "public.posts" }

// User — Application user accounts.
type User struct {
	// Stable user identifier.
	ID int64 `db:"id" gorm:"column:id;primaryKey;not null" json:"id"`
	// Unique login email.
	Email       string           `db:"email" gorm:"column:email;not null" json:"email"`
	DisplayName *string          `db:"display_name" gorm:"column:display_name" json:"display_name,omitempty"`
	Role        UserRole         `db:"role" gorm:"column:role;not null" json:"role"`
	CreatedAt   time.Time        `db:"created_at" gorm:"column:created_at;not null;default:now()" json:"created_at,omitempty"`
	DeletedAt   *time.Time       `db:"deleted_at" gorm:"column:deleted_at" json:"deleted_at,omitempty"`
	Metadata    *json.RawMessage `db:"metadata" gorm:"column:metadata" json:"metadata,omitempty"`
}

// TableName implements the gorm table-name interface.
func (User) TableName() string { return "public.users" }
