// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

/** Composite type public.address. */
export interface Address {
  street: string;
  city: string;
  zip: string;
}

/** Domain public.short_text over text. */
export type ShortText = string;

