// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

/** Input parameters for public.calculate_score. */
export interface CalculateScoreParams {
  user_id: bigint;
  weight?: string;
}

/** One row returned by public.calculate_score. */
export interface CalculateScoreResult {
  score: string;
  tier: string;
}

/** Input parameters for public.length_of. */
export interface LengthOfParams {
  s: string;
}

/** Scalar value returned by public.length_of. */
export type LengthOfRow = number;

