// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

/** Read-only row from view public.active_users. */
export interface ActiveUser {
  id: bigint | null;
  email: string | null;
  last_seen: Date | null;
}

