// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

// ActiveUser — Read-only row from view public.active_users.
type ActiveUser struct {
	// fields: not yet inferred from view definition;
	// add manually or override via codegen config.
}
