// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

import (
	"time"
)

// ActiveUser — Read-only row from view public.active_users.
type ActiveUser struct {
	ID       *int64     `db:"id" gorm:"column:id" json:"id,omitempty"`
	Email    *string    `db:"email" gorm:"column:email" json:"email,omitempty"`
	LastSeen *time.Time `db:"last_seen" gorm:"column:last_seen" json:"last_seen,omitempty"`
}
