// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

/** Application user accounts. */
export interface User {
  /** Stable user identifier. */
  id: bigint;
  /** Unique login email. */
  email: string;
  display_name: string | null;
  role: UserRole;
  created_at: Date;
  deleted_at: Date | null;
  metadata: unknown | null;
}

