package codegen

import (
	"fmt"
	"os"
)

// DefaultConfigYAML is the auto-scaffolded codegen config that `pg-flux gen init`
// writes to disk. Every option is documented inline so users can keep what they
// need and delete the rest. The defaults match the emitter's zero-value
// behaviour (no surprises): snake_case keys, bigint, Date, T | null nullable,
// string-union enums, no validators, no ORM tags.
const DefaultConfigYAML = `# .pg-flux-codegen.yml
# Auto-generated by ` + "`pg-flux gen init`" + `. Tune the options below to your stack.
# Re-run ` + "`pg-flux gen`" + ` after every migrate; use --check in CI to gate on stale output.

outputs:
  - lang: go
    out: ./internal/dbgen
    package: dbgen
    # ORM tag flavor — controls what struct tags get emitted:
    #   ""     (default) — db + json tags only
    #   sqlx            — db tag only (sqlx ignores json)
    #   gorm            — adds gorm:"primaryKey;autoIncrement;..." plus a TableName() method
    #   bun             — adds bun:"id,pk,autoincrement,..." plus TableName()
    #   ent             — minimal ent compatibility
    # orm_tags: ""

    # json:",omitempty" rules:
    #   ""        (default) — never omitempty
    #   nullable           — only nullable columns
    #   defaults           — nullable + columns with DEFAULTs / identity / generated
    #   all                — every column
    # omitempty: ""

    # readonly marker: which columns get a "// readonly" comment.
    # values: none (default), identity, generated, defaults, all
    # readonly: none

    # Custom PG type → Go type. Values may be fully-qualified import paths.
    # type_overrides:
    #   numeric: github.com/shopspring/decimal.Decimal
    #   uuid:    github.com/google/uuid.UUID

    # Emit Params + Result types for user-defined functions and procedures.
    # Default off because large schemas often have many helper fns.
    # functions: false

  - lang: ts
    out: ./src/db
    # bigint / int8 / bigserial mapping:
    #   bigint (default) — native bigint; not JSON-safe
    #   number          — JS number; loses precision above 2^53
    #   string          — string preserves precision through JSON
    bigint_as: bigint

    # timestamp* / date / time mapping:
    #   Date (default) — JS Date
    #   string         — ISO 8601 string (recommended for JSON APIs)
    #   temporal       — Temporal.Instant (stage-3 proposal)
    date_as: Date

    # null style for nullable columns:
    #   union (default) — field: T | null
    #   undefined       — field: T | undefined
    #   optional        — field?: T
    null_style: union

    # enum style:
    #   union (default)   — type Role = "a" | "b"
    #   const-object      — const Role = { A: "a", B: "b" } as const; type Role = ...
    #   ts-enum           — TypeScript enum keyword (runtime values + reverse map)
    enum_style: union

    # column key naming (default snake):
    #   snake  — verbatim (created_at)
    #   camel  — JS convention (createdAt)
    #   pascal — (CreatedAt)
    # column_case: snake

    # readonly: see Go section. TS emits the readonly keyword on properties.
    # readonly: none

    # Branded ID types: type UserId = bigint & { readonly __brand: "UserId" }.
    # Prevents passing a PostId where a UserId is expected.
    # branded_ids: false

    # Insert<T> and Update<T> partial helper types for write paths.
    # insert_update_helpers: false

    # Emit a parallel validators.ts with zod schemas alongside the types.
    #   ""    (default) — no validators
    #   zod              — z.object schemas matching every type
    # validators: ""

    # Per-column jsonb shapes. Keys are "schema.table.column"; values are
    # TS type expressions emitted verbatim. Replaces "unknown".
    # json_shapes:
    #   public.users.metadata: '{ source: string; ip: string }'

    # type_overrides:
    #   numeric: string
    #   uuid:    string

    # Emit Params + Result interfaces for user-defined functions / procedures.
    # functions: false

# Filtering — apply per output target.
# include_tables: ["users", "posts"]        # allowlist (matches schema.name or name)
# exclude_tables: ["_pgflux_*", "audit_*"]  # denylist (glob patterns)
# exclude_schemas: ["_pgflux", "audit"]     # skip whole schemas
`

// WriteDefaultConfig scaffolds .pg-flux-codegen.yml at path. Refuses to
// overwrite an existing file unless force is set.
func WriteDefaultConfig(path string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("refusing to overwrite %s (re-run with --force)", path)
	}
	return os.WriteFile(path, []byte(DefaultConfigYAML), 0o644)
}
