package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/nex-gen-tech/pg-flux/pkg/schema"
)

// RustGenerator emits Rust type definitions compatible with sqlx (FromRow,
// Type derives) and serde (Serialize, Deserialize). Output follows the
// per-kind layout: tables.rs, enums.rs, views.rs, types.rs, functions.rs,
// and a mod.rs barrel that re-exports all modules.
type RustGenerator struct {
	NameOverrides map[string]string
}

// NewRustGenerator returns a RustGenerator with default settings.
func NewRustGenerator() *RustGenerator { return &RustGenerator{} }

// Lang implements Generator.
func (g *RustGenerator) Lang() Language { return LangRust }

// Generate implements Generator.
func (g *RustGenerator) Generate(s *schema.SchemaState, opts Options) (FileSet, error) {
	if s == nil {
		return FileSet{}, nil
	}
	opts.Emit.normalize()
	s = opts.Emit.Filter.ApplyToState(s)

	tm := opts.TypeMap
	if tm == nil {
		tm = &RustTypeMap{}
	}
	if rtm, ok := tm.(*RustTypeMap); ok {
		rtm.CustomTypes = g.collectCustomTypes(s)
	}

	out := FileSet{}
	var modules []string

	if content, ok := g.emitTables(s, tm, opts); ok {
		out["tables.rs"] = []byte(trimTrailingBlankLines(content))
		modules = append(modules, "tables")
	}
	if content, ok := g.emitEnums(s); ok {
		out["enums.rs"] = []byte(trimTrailingBlankLines(content))
		modules = append(modules, "enums")
	}
	if content, ok := g.emitViews(s, tm, opts); ok {
		out["views.rs"] = []byte(trimTrailingBlankLines(content))
		modules = append(modules, "views")
	}
	if content, ok := g.emitTypes(s, tm, opts); ok {
		out["types.rs"] = []byte(trimTrailingBlankLines(content))
		modules = append(modules, "types")
	}
	if content, ok := g.emitFunctions(s, tm, opts); ok {
		out["functions.rs"] = []byte(trimTrailingBlankLines(content))
		modules = append(modules, "functions")
	}
	if len(modules) > 0 {
		out["mod.rs"] = []byte(g.emitModRs(modules))
	}
	return out, nil
}

// fileHeader returns the standard generated-file header with the given use declarations.
func (g *RustGenerator) fileHeader(uses []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by pg-flux. DO NOT EDIT.\n")
	b.WriteString("// To regenerate, run: pg-flux gen --lang rust\n\n")
	// serde is always needed when structs/enums are present.
	b.WriteString("#![allow(dead_code)]\n\n")
	b.WriteString("use serde::{Deserialize, Serialize};\n")
	// Additional use declarations (sorted, deduplicated).
	deduped := uniqueSort(uses)
	for _, u := range deduped {
		fmt.Fprintf(&b, "use %s;\n", u)
	}
	b.WriteString("\n")
	return b.String()
}

// typeName converts a PG schema+name pair to PascalCase Rust identifier.
func (g *RustGenerator) typeName(schName, objName string) string {
	full := schName + "." + objName
	if g.NameOverrides != nil {
		if v, ok := g.NameOverrides[full]; ok {
			return v
		}
		if v, ok := g.NameOverrides[objName]; ok {
			return v
		}
	}
	return PascalCaseInit(Singular(objName))
}

// enumTypeName is like typeName but does NOT singularize — enum types should
// keep their original name (e.g. "user_role" → "UserRole", not "UserRol").
func (g *RustGenerator) enumTypeName(schName, objName string) string {
	full := schName + "." + objName
	if g.NameOverrides != nil {
		if v, ok := g.NameOverrides[full]; ok {
			return v
		}
		if v, ok := g.NameOverrides[objName]; ok {
			return v
		}
	}
	return PascalCaseInit(objName)
}

// --- tables.rs ---

func (g *RustGenerator) emitTables(s *schema.SchemaState, tm TypeMap, opts Options) (string, bool) {
	if len(s.Tables) == 0 {
		return "", false
	}
	var body strings.Builder
	var uses []string

	for _, k := range SortedKeys(s.Tables) {
		t := s.Tables[k]
		if t == nil {
			continue
		}
		typeName := g.typeName(t.Schema, t.Name)
		comment := t.Comment
		if comment == "" {
			comment = fmt.Sprintf("mirrors %s.%s.", t.Schema, t.Name)
		}
		fmt.Fprintf(&body, "/// %s %s\n", typeName, comment)
		body.WriteString("#[derive(Debug, Clone, sqlx::FromRow, Serialize, Deserialize)]\n")
		fmt.Fprintf(&body, "pub struct %s {\n", typeName)
		for _, c := range t.Columns {
			if c == nil {
				continue
			}
			isNullable := !c.NotNull
			isGenerated := c.GeneratedKind == "stored" || c.GeneratedKind == "virtual"
			typeExpr, imps := tm.Map(c.TypeSQL, isNullable || isGenerated)
			uses = append(uses, rustUseDecls(imps)...)
			fieldName := SnakeCase(c.Name)
			// Emit a rename attribute if the field name differs from the column name.
			if fieldName != c.Name {
				fmt.Fprintf(&body, "    #[sqlx(rename = %q)]\n", c.Name)
			}
			if isReadonly(c, opts.Emit.Readonly) {
				body.WriteString("    // readonly: server-managed\n")
			}
			fmt.Fprintf(&body, "    pub %s: %s,\n", fieldName, typeExpr)
		}
		body.WriteString("}\n\n")
	}

	header := g.fileHeader(uses)
	return header + body.String(), true
}

// --- enums.rs ---

func (g *RustGenerator) emitEnums(s *schema.SchemaState) (string, bool) {
	if len(s.EnumValues) == 0 {
		return "", false
	}
	var body strings.Builder

	for _, k := range SortedKeys(s.EnumValues) {
		values := s.EnumValues[k]
		parts := strings.SplitN(k, ".", 2)
		var schName, name string
		if len(parts) == 2 {
			schName, name = parts[0], parts[1]
		} else {
			schName, name = "public", parts[0]
		}
		typeName := g.enumTypeName(schName, name)
		fmt.Fprintf(&body, "/// %s mirrors PG enum %s.%s.\n", typeName, schName, name)
		body.WriteString("#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, sqlx::Type)]\n")
		fmt.Fprintf(&body, "#[sqlx(type_name = %q)]\n", name)
		fmt.Fprintf(&body, "pub enum %s {\n", typeName)
		for _, v := range values {
			variantName := PascalCaseInit(strings.ReplaceAll(v, "-", "_"))
			if variantName == "" {
				variantName = "Unknown"
			}
			fmt.Fprintf(&body, "    #[sqlx(rename = %q)]\n", v)
			fmt.Fprintf(&body, "    #[serde(rename = %q)]\n", v)
			fmt.Fprintf(&body, "    %s,\n", variantName)
		}
		body.WriteString("}\n\n")
	}

	header := g.fileHeader(nil)
	return header + body.String(), true
}

// --- views.rs ---

func (g *RustGenerator) emitViews(s *schema.SchemaState, tm TypeMap, opts Options) (string, bool) {
	if len(s.Views) == 0 {
		return "", false
	}
	var body strings.Builder
	var uses []string

	for _, k := range SortedKeys(s.Views) {
		v := s.Views[k]
		if v == nil {
			continue
		}
		typeName := g.typeName(v.Schema, v.Name)
		kw := "view"
		if v.Materialized {
			kw = "materialized view"
		}
		comment := v.Comment
		if comment == "" {
			comment = fmt.Sprintf("is a read-only row from %s %s.%s.", kw, v.Schema, v.Name)
		}
		fmt.Fprintf(&body, "/// %s %s\n", typeName, comment)
		body.WriteString("#[derive(Debug, Clone, sqlx::FromRow, Serialize, Deserialize)]\n")
		fmt.Fprintf(&body, "pub struct %s {\n", typeName)
		if len(v.Columns) == 0 {
			body.WriteString("    // fields: not yet inferred from view definition\n")
		}
		for _, c := range v.Columns {
			if c == nil {
				continue
			}
			// View columns are always nullable.
			typeExpr, imps := tm.Map(c.TypeSQL, true)
			uses = append(uses, rustUseDecls(imps)...)
			fieldName := SnakeCase(c.Name)
			if fieldName != c.Name {
				fmt.Fprintf(&body, "    #[sqlx(rename = %q)]\n", c.Name)
			}
			fmt.Fprintf(&body, "    pub %s: %s,\n", fieldName, typeExpr)
		}
		body.WriteString("}\n\n")
	}

	header := g.fileHeader(uses)
	return header + body.String(), true
}

// --- types.rs (composite types + domains) ---

func (g *RustGenerator) emitTypes(s *schema.SchemaState, tm TypeMap, opts Options) (string, bool) {
	if len(s.CompositeTypes) == 0 && len(s.Domains) == 0 {
		return "", false
	}
	var body strings.Builder
	var uses []string

	for _, k := range SortedKeys(s.CompositeTypes) {
		ct := s.CompositeTypes[k]
		if ct == nil {
			continue
		}
		typeName := g.typeName(ct.Schema, ct.Name)
		comment := ct.Comment
		if comment == "" {
			comment = fmt.Sprintf("mirrors composite type %s.%s.", ct.Schema, ct.Name)
		}
		fmt.Fprintf(&body, "/// %s %s\n", typeName, comment)
		body.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")
		fmt.Fprintf(&body, "pub struct %s {\n", typeName)
		for _, a := range ct.Attributes {
			typeExpr, imps := tm.Map(a.Type, false)
			uses = append(uses, rustUseDecls(imps)...)
			fieldName := SnakeCase(a.Name)
			if fieldName != a.Name {
				fmt.Fprintf(&body, "    #[serde(rename = %q)]\n", a.Name)
			}
			fmt.Fprintf(&body, "    pub %s: %s,\n", fieldName, typeExpr)
		}
		body.WriteString("}\n\n")
	}

	for _, k := range SortedKeys(s.Domains) {
		d := s.Domains[k]
		if d == nil {
			continue
		}
		typeName := g.typeName(d.Schema, d.Name)
		baseExpr, imps := tm.Map(d.BaseType, false)
		uses = append(uses, rustUseDecls(imps)...)
		fmt.Fprintf(&body, "/// %s mirrors domain %s.%s over %s.\n", typeName, d.Schema, d.Name, d.BaseType)
		body.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")
		fmt.Fprintf(&body, "pub struct %s(pub %s);\n\n", typeName, baseExpr)
	}

	header := g.fileHeader(uses)
	return header + body.String(), true
}

// --- functions.rs ---

func (g *RustGenerator) emitFunctions(s *schema.SchemaState, tm TypeMap, opts Options) (string, bool) {
	if !opts.Emit.Functions || len(s.Functions) == 0 {
		return "", false
	}
	var body strings.Builder
	var uses []string
	any := false

	for _, k := range SortedKeys(s.Functions) {
		f := s.Functions[k]
		if !shouldEmitFn(f) {
			continue
		}
		fnName := fnTypeName(f, g.NameOverrides)

		if len(f.Args) > 0 {
			fmt.Fprintf(&body, "/// %sParams holds the input parameters for %s.%s.\n", fnName, f.Schema, f.Name)
			body.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")
			fmt.Fprintf(&body, "pub struct %sParams {\n", fnName)
			for i, a := range f.Args {
				name := paramName(a, i)
				fieldName := SnakeCase(name)
				typeExpr, imps := tm.Map(a.Type, false)
				uses = append(uses, rustUseDecls(imps)...)
				if fieldName != name {
					fmt.Fprintf(&body, "    #[serde(rename = %q)]\n", name)
				}
				fmt.Fprintf(&body, "    pub %s: %s,\n", fieldName, typeExpr)
			}
			body.WriteString("}\n\n")
			any = true
		}

		if f.Kind == "p" {
			continue
		}

		if len(f.ReturnsTable) > 0 {
			fmt.Fprintf(&body, "/// %sResult is one row returned by %s.%s.\n", fnName, f.Schema, f.Name)
			body.WriteString("#[derive(Debug, Clone, sqlx::FromRow, Serialize, Deserialize)]\n")
			fmt.Fprintf(&body, "pub struct %sResult {\n", fnName)
			for _, a := range f.ReturnsTable {
				name := paramName(a, 0)
				fieldName := SnakeCase(name)
				typeExpr, imps := tm.Map(a.Type, false)
				uses = append(uses, rustUseDecls(imps)...)
				if fieldName != name {
					fmt.Fprintf(&body, "    #[sqlx(rename = %q)]\n", name)
				}
				fmt.Fprintf(&body, "    pub %s: %s,\n", fieldName, typeExpr)
			}
			body.WriteString("}\n\n")
			any = true
		} else if f.ReturnType != "" && !isVoidLike(f.ReturnType) {
			typeExpr, imps := tm.Map(f.ReturnType, false)
			uses = append(uses, rustUseDecls(imps)...)
			fmt.Fprintf(&body, "/// %sRow is the scalar value returned by %s.%s.\n", fnName, f.Schema, f.Name)
			fmt.Fprintf(&body, "pub type %sRow = %s;\n\n", fnName, typeExpr)
			any = true
		}
	}

	if !any {
		return "", false
	}
	header := g.fileHeader(uses)
	return header + body.String(), true
}

// --- mod.rs ---

func (g *RustGenerator) emitModRs(modules []string) string {
	sort.Strings(modules)
	var b strings.Builder
	b.WriteString("// Code generated by pg-flux. DO NOT EDIT.\n")
	b.WriteString("// To regenerate, run: pg-flux gen --lang rust\n\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "pub mod %s;\n", m)
	}
	return b.String()
}

// collectCustomTypes builds the PG user-defined-type → Rust identifier map.
func (g *RustGenerator) collectCustomTypes(s *schema.SchemaState) map[string]string {
	if s == nil {
		return nil
	}
	out := map[string]string{}
	for k := range s.EnumValues {
		parts := strings.SplitN(k, ".", 2)
		var sch, n string
		if len(parts) == 2 {
			sch, n = parts[0], parts[1]
		} else {
			sch, n = "public", parts[0]
		}
		ident := g.enumTypeName(sch, n)
		out[k] = ident
		out[n] = ident
	}
	for k, ct := range s.CompositeTypes {
		if ct == nil {
			continue
		}
		ident := g.typeName(ct.Schema, ct.Name)
		out[k] = ident
		out[ct.Name] = ident
	}
	for k, d := range s.Domains {
		if d == nil {
			continue
		}
		ident := g.typeName(d.Schema, d.Name)
		out[k] = ident
		out[d.Name] = ident
	}
	return out
}

// rustUseDecls converts crate-name import tags (e.g. "uuid", "chrono",
// "serde_json") into fully-qualified use statements. Returns nil for
// types that need no explicit use (String, i64, bool, etc.).
func rustUseDecls(imps []string) []string {
	var decls []string
	for _, imp := range imps {
		switch imp {
		case "uuid":
			decls = appendUniq(decls, "uuid::Uuid")
		// chrono and serde_json use fully-qualified paths in field types;
		// no use import needed — just record for Cargo.toml awareness.
		// (We skip them here to avoid polluting `use` with unused paths.)
		}
	}
	return decls
}
