package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/nex-gen-tech/pg-flux/pkg/schema"
)

// PythonGenerator emits a single models.py with Pydantic v2 BaseModel classes
// (one per table) and str+Enum classes (one per PG enum type). It always emits
// a single-file layout to match Python conventions.
type PythonGenerator struct {
	NameOverrides map[string]string
}

// NewPythonGenerator returns a PythonGenerator with default settings.
func NewPythonGenerator() *PythonGenerator { return &PythonGenerator{} }

// Lang implements Generator.
func (g *PythonGenerator) Lang() Language { return LangPython }

// Generate implements Generator. It produces a single "models.py" file in opts.OutDir.
func (g *PythonGenerator) Generate(s *schema.SchemaState, opts Options) (FileSet, error) {
	if s == nil {
		return FileSet{}, nil
	}
	opts.Emit.normalize()
	s = opts.Emit.Filter.ApplyToState(s)

	// Build the custom-type map so the typemap can resolve enum column refs.
	ptm := g.buildTypeMap(s, opts)

	var b strings.Builder
	b.WriteString("# Code generated by pg-flux. DO NOT EDIT.\n")
	b.WriteString("# To regenerate, run: pg-flux gen --lang python\n\n")

	// Collect which imports are actually needed.
	needed := newImportSet()

	// --- Emit enums first (tables may reference them) ---
	var enumBuf strings.Builder
	for _, k := range SortedKeys(s.EnumValues) {
		values := s.EnumValues[k]
		parts := strings.SplitN(k, ".", 2)
		var schName, name string
		if len(parts) == 2 {
			schName, name = parts[0], parts[1]
		} else {
			schName, name = "public", parts[0]
		}
		className := g.typeName(schName, name)
		needed.add("Enum")
		fmt.Fprintf(&enumBuf, "\nclass %s(str, Enum):\n", className)
		for _, v := range values {
			pyName := strings.ToUpper(strings.ReplaceAll(v, "-", "_"))
			fmt.Fprintf(&enumBuf, "    %s = %q\n", pyName, v)
		}
		enumBuf.WriteString("\n")
	}

	// --- Emit table models ---
	var tableBuf strings.Builder
	for _, k := range SortedKeys(s.Tables) {
		t := s.Tables[k]
		if t == nil {
			continue
		}
		className := g.typeName(t.Schema, t.Name)
		needed.add("BaseModel")
		fmt.Fprintf(&tableBuf, "\nclass %s(BaseModel):\n", className)
		if len(t.Columns) == 0 {
			tableBuf.WriteString("    pass\n\n")
			continue
		}
		for _, c := range t.Columns {
			if c == nil {
				continue
			}
			isNullable := !c.NotNull
			isGenerated := c.GeneratedKind == "stored" || c.GeneratedKind == "virtual"
			hasDefault := c.DefaultSQL != "" || c.Identity != ""

			typeExpr, imps := ptm.Map(c.TypeSQL, isNullable || isGenerated)
			for _, imp := range imps {
				needed.add(imp)
			}

			var fieldParts strings.Builder
			fmt.Fprintf(&fieldParts, "    %s: %s", c.Name, typeExpr)

			// Determine whether to add a default value.
			switch {
			case isGenerated:
				// Server-computed: always Optional with None default.
				fieldParts.WriteString(" = None  # server-computed")
			case isNullable:
				// Nullable: default to None.
				fieldParts.WriteString(" = None")
			case hasDefault:
				// Has a database default but NOT NULL: emit = None so callers
				// can omit the field in INSERT payloads; the DB fills it in.
				// Re-wrap the type to Optional to allow the Python-side None.
				if !strings.HasPrefix(typeExpr, "Optional[") {
					needed.add("Optional")
					typeExpr = "Optional[" + typeExpr + "]"
					// Rewrite the field line.
					fieldParts.Reset()
					fmt.Fprintf(&fieldParts, "    %s: %s = None", c.Name, typeExpr)
				} else {
					fieldParts.WriteString(" = None")
				}
			}

			tableBuf.WriteString(fieldParts.String())
			tableBuf.WriteString("\n")
		}
		tableBuf.WriteString("\n")
	}

	// --- Build the import block ---
	b.WriteString("from __future__ import annotations\n")
	if needed.has("datetime") {
		b.WriteString("from datetime import datetime\n")
	}
	if needed.has("Decimal") {
		b.WriteString("from decimal import Decimal\n")
	}
	if needed.has("Enum") {
		b.WriteString("from enum import Enum\n")
	}
	if needed.has("Optional") || needed.has("Any") {
		var typingSymbols []string
		if needed.has("Optional") {
			typingSymbols = append(typingSymbols, "Optional")
		}
		if needed.has("Any") {
			typingSymbols = append(typingSymbols, "Any")
		}
		sort.Strings(typingSymbols)
		fmt.Fprintf(&b, "from typing import %s\n", strings.Join(typingSymbols, ", "))
	}
	if needed.has("UUID") {
		b.WriteString("from uuid import UUID\n")
	}
	if needed.has("BaseModel") {
		b.WriteString("\nfrom pydantic import BaseModel\n")
	}

	b.WriteString(enumBuf.String())
	b.WriteString(tableBuf.String())

	content := trimTrailingBlankLines(b.String())
	return FileSet{"models.py": []byte(content)}, nil
}

// typeName converts a PG schema+name pair to a Python CamelCase class name.
// It applies the user's NameOverrides first, then PascalCase (no Singular —
// Python classes for tables are typically plural or match the table name).
func (g *PythonGenerator) typeName(schName, objName string) string {
	full := schName + "." + objName
	if g.NameOverrides != nil {
		if v, ok := g.NameOverrides[full]; ok {
			return v
		}
		if v, ok := g.NameOverrides[objName]; ok {
			return v
		}
	}
	return PascalCase(objName)
}

// buildTypeMap constructs the PythonTypeMap wired to custom enum types.
func (g *PythonGenerator) buildTypeMap(s *schema.SchemaState, opts Options) *PythonTypeMap {
	var ptm *PythonTypeMap
	if opts.TypeMap != nil {
		if existing, ok := opts.TypeMap.(*PythonTypeMap); ok {
			ptm = existing
		}
	}
	if ptm == nil {
		ptm = &PythonTypeMap{}
	}
	ptm.CustomTypes = g.collectCustomTypes(s)
	return ptm
}

// collectCustomTypes builds the PG user-defined-type → Python class name map.
func (g *PythonGenerator) collectCustomTypes(s *schema.SchemaState) map[string]string {
	if s == nil {
		return nil
	}
	out := map[string]string{}
	for k := range s.EnumValues {
		parts := strings.SplitN(k, ".", 2)
		var sch, n string
		if len(parts) == 2 {
			sch, n = parts[0], parts[1]
		} else {
			sch, n = "public", parts[0]
		}
		ident := g.typeName(sch, n)
		out[k] = ident
		out[n] = ident
	}
	return out
}

// importSet tracks which Python symbols are needed in the file header.
type importSet struct {
	m map[string]bool
}

func newImportSet() *importSet { return &importSet{m: map[string]bool{}} }

func (s *importSet) add(sym string) { s.m[sym] = true }

func (s *importSet) has(sym string) bool { return s.m[sym] }
