// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

/** PG enum public.user_role */
export const UserRole = {
  Admin: "admin",
  Member: "member",
  Guest: "guest",
} as const;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];

