// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

/** Row from public.posts. */
export interface Post {
  id: PostId;
  title: string;
  tags?: string[];
  readonly viewCount: number;
}

export type InsertPost = Omit<Post, "tags" | "viewCount"> & Partial<Pick<Post, "tags" | "viewCount">>;
export type UpdatePost = Partial<Post>;

/** Application user accounts. */
export interface User {
  /** Stable user identifier. */
  id: UserId;
  /** Unique login email. */
  email: string;
  displayName?: string;
  role: UserRole;
  readonly createdAt: string;
  deletedAt?: string;
  metadata?: unknown;
}

export type InsertUser = Omit<User, "displayName" | "createdAt" | "deletedAt" | "metadata"> & Partial<Pick<User, "displayName" | "createdAt" | "deletedAt" | "metadata">>;
export type UpdateUser = Partial<User>;

