// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

import { z } from "zod";

export const UserRoleSchema = z.enum(["admin", "member", "guest"]);

export const AddressSchema = z.object({
  street: z.string(),
  city: z.string(),
  zip: z.string(),
});

export const PostSchema = z.object({
  id: z.number(),
  title: z.string(),
  tags: z.array(z.string()).nullable(),
  viewCount: z.number(),
});

export const UserSchema = z.object({
  id: z.number(),
  email: z.string(),
  displayName: z.string().nullable(),
  role: UserRoleSchema,
  createdAt: z.string(),
  deletedAt: z.string().nullable(),
  metadata: z.unknown().nullable(),
});

