// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

/** Read-only row from view public.active_users. */
export interface ActiveUser {
  id?: number;
  email?: string;
  lastSeen?: string;
}

