// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

// CalculateScoreParams are the input parameters for public.calculate_score.
type CalculateScoreParams struct {
	UserID int64  `db:"user_id" json:"user_id"`
	Weight string `db:"weight" json:"weight"`
}

// CalculateScoreResult is one row returned by public.calculate_score.
type CalculateScoreResult struct {
	Score string `db:"score" json:"score"`
	Tier  string `db:"tier" json:"tier"`
}

// LengthOfParams are the input parameters for public.length_of.
type LengthOfParams struct {
	S string `db:"s" json:"s"`
}

// LengthOfRow is the scalar value returned by public.length_of.
type LengthOfRow = int32
