// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

package dbgen

import (
	"encoding/json"
	"time"
)

// Post mirrors public.posts.
type Post struct {
	ID        int64     `db:"id"`
	Title     string    `db:"title"`
	Tags      *[]string `db:"tags"`
	ViewCount int32     `db:"view_count"`
}

// User — Application user accounts.
type User struct {
	// Stable user identifier.
	ID int64 `db:"id"`
	// Unique login email.
	Email       string           `db:"email"`
	DisplayName *string          `db:"display_name"`
	Role        UserRole         `db:"role"`
	CreatedAt   time.Time        `db:"created_at"`
	DeletedAt   *time.Time       `db:"deleted_at"`
	Metadata    *json.RawMessage `db:"metadata"`
}
