// Code generated by pg-flux. DO NOT EDIT.
// To regenerate, run: pg-flux gen

export type PostId = number & { readonly __brand: "PostId" };
export type UserId = number & { readonly __brand: "UserId" };
